# Generated by Django 5.0.4 on 2025-05-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('3d', '3D Models'), ('2d', '2D Art'), ('audio', 'Audio'), ('scripts', 'Scripts')], default='3d', max_length=50),
        ),
    ]
